name: CI_DEV_PR
on:
  pull_request:
    branches:
      - dev

jobs:
  push:
    strategy:
      matrix:
        node-version: [16.x]

    name: PR
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci --ignore-scripts
      - run: npm run lint && npm run format && npm run build
          
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Dev PR processed"

